version: "3.3"

services:
  neo4j:
    image: neo4j:5.5.0
    environment:
      - NEO4J_AUTH=neo4j/smartbsmartb
    ports:
      - 7687:7687
      - 7474:7474  # browser interface (localhost:7474)
    volumes:
      - ./infra/dev/neo4j/data:/data
